addded camera models
SalientSys/salient-sys-cloud-dtos pull request #17
Opened 2023-02-06 02:40 UTC by dante-salient

2023-02-06 15:59 UTC, TonyH-Salient requested changes

2023-02-06 15:59 UTC, TonyH-Salient commented on src/dtos/recording-server/cameras/cone.model.ts
> +export type Cone = {
Can this be a regular interface? `export interface Cone {}`?

2023-02-06 15:59 UTC, TonyH-Salient commented on src/dtos/recording-server/cameras/ptz-settings.model.ts
> +    presets?: PresetsEntity[] | null;
Name can be shorten to `presets: PtzPreset[] | null;`

2023-02-06 15:59 UTC, TonyH-Salient commented on src/dtos/recording-server/cameras/camera.model.ts
> +  nvrCamera: any | null;
It might be good to leave out the unnecessary properties for now. IIRC, we can just the list of properties that are being used in the WC here https://tfs.salientsys.com/tfs/SalientSystemsCollection/CompleteView/_git/Gen4WebClient?path=%2Fsrc%2Fapp%2Fmodels%2Fresponses%2Fcamera-responses%2Fcamera.model.ts&version=GBmaster&line=56&lineEnd=67&lineStartColumn=3&lineEndColumn=16&lineStyle=plain

2023-02-06 20:59 UTC, dante-salient commented on src/dtos/recording-server/cameras/ptz-settings.model.ts
> +    presets?: PresetsEntity[] | null;
523f618e87518cc81f79c1c2077268a55fa2abb3

2023-02-06 20:59 UTC, dante-salient commented on src/dtos/recording-server/cameras/camera.model.ts
> +  nvrCamera: any | null;
d51ff6083b5ee5b35f693aaf1798b1a37ca46744

2023-02-07 22:22 UTC, TonyH-Salient approved these changes

2023-02-08 21:25 UTC, SohailHaqyar approved these changes

2023-02-09 13:33 UTC, merged